---
output: 
  html_document:
    includes:
      before_body: header_blogpage.html
title: "Elections 2020: Arizona State Legislature"
params: 
    set_title: "JB - Elections 2020: Arizona State Legislature"
mainfont: Verdana
---
<div class="mainbody" style="top: 0;"> joseph broad <-
<div class="wrapper" style="height: auto">
<div class="section">
<h2>Elections 2020: Arizona State Senate</h2>
<p2><br>Quick Overview:<br><br>
Some political observers (especially liberal observers) have bemoaned the lack of academic attention given to state and local elections. Here I take a brief look into elections for the Arizona State Senate as part of a larger project aiming to fill the gap in academic attention to elections in state legislatures.<br><br>
Arizona state senate election outcomes can be predicted with nearly 100% accuracy with just one variable: the major party registration differential. Republicans have had a registration advantage in most districts for years (since the 1970s, when party labels were more confounding than informative). Democrats have not come this close to taking a majority in one of the state legislative bodies since 2000, when a tie in the Senate led to Democrats and Republicans splitting power.<br><br> 
To aid a discussion of elections for state office, I constructed the interactive map below. The graphic displays state senate legislative districts, colored according to its major party voter registration differential. The panel at the top right displays the 2018 election outcomes for both the state House and Senate. The panel on the bottom right shows the trend of this differential since 2012, as well as a forecast of the registration differential into 2020. As the reader can see, very few districts are competitive; in all but two districts, the proportion of one party exceeds the proportion of the other by more than five points (a standard benchmark for competitiveness in political science).<br><br>
</p2>
</div>

<div style="height: 74vh; width: 80%; min-width: 1200px; margin: auto">
<iframe src="https://josephbroad.shinyapps.io/shiny/" style="border: 1px solid #A3350D; width: 100%; height: 100%; -webkit-transform:scale(0.85); -moz-transform-scale(0.85);"></iframe></div>

<div class="section" style="text-align: left;">
<p2>
If the 2020 election were to take place today (the vertical red line indicates registration data as of October 2019), districts 8 (Frank Pratt - R) and 18 (Sean Bowie - D) would be highly competitive. The remaining 28 legislative districts would be highly likely to retain their current party representation. This is highly problematic for Democrats, as they need to pick up three seats and retain district 18 to gain a majority in the Senate. However, the registration trends above show sudden (and at times drastic) bumps and dips as national and state-wide campaign efforts get into gear.<br><br>
The results of a simple forecasting model based on past trends in the registration differential are shown in the bottom right panel beyond the vertical red line. These results suggest that should the Democrats organize as successfully as they did in 2016, two additional senate districts will be competitive: districts 20 (Paul Boyer - R) and 28 (Kate Brophy McGee - R). Some may argue district 28 is competitive today, given that it is represented by two Democrats in the state house, and they are probably correct. There are a number of others that are on the cusp of competitive based on registration projections: districts 17, 6, 21 (from most likely to least). Notice that in district 21, there was essentially no bump in Democrat registration relative to Republicans in 2016. Their fight here will most definiltey be uphill.<br><br>
I should reiterate here that this brief overview is based on the assumption that state Democrats will organize as well as they have in past elections. This assumption is not too far-fetched, given that there is a trend in local elections to become more nationalized (i.e. the issues that matter in local elections have become increasingly federal or national issues or related to national public figures).<br><br> 
That said, this nationalization trend should help Democrats next fall given the difference between political contexts in 2020 and 2016. In 2016, Democrats had to contend with the late Senator John McCain and his campaign team. An unpopular Democratic nominee made mobilizing moderate voters in Arizona more difficult than it needed to be. Additionally, there is a tendency for the moderate public to swing to the other party after so many years of one party's control. In 2020, Democrats will certainly have a different set of challenges, but it's a good sign that they will not have to face these three challenges that were present in 2016.<br><br>
In this scenario, Democrats may actually have a shot at taking the Senate and the House. Keep in mind, however, that these forecasts are made with just the major party differential variable and do not take into account the behavior of Independents, who make up a vast proportion of voters in Arizona. Their voting behavior is key in competitive districts as well as some not-so-competitive districts.<br><br>
Take district 28, for example: this district's major-party differential in 2018 would have classified it as solid Republican, and yet both house seats were won by Democrats. Similarly, the two-party differential for district 17 in 2018 would have classified this district as solid Republican but one of its house seats went to a Democrat and the Republican senate seat was won by less than a one-percent margin.<br><br>
Stay tuned for a more sophisticated prediction of 2020 election outcomes including predictions of Independent behavior and the role money plays in state election outcomes.
</p2>
</div>
<div class="section" style="top: 0; text-align: left; margin-left: 20vw; width: 60vw; border: 2px none red; height: 10vh;"></div></div></div>












