---
output: html_document
params: 
    set_title: "Data Visualization"
title: "`r params$set_title`"
---

<!-- Load an icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- style -->
<link rel="stylesheet" href="style.css" type="text/css">
<!-- header -->
<div class="flex-container">
<div class="topnav"><a href="index.html"><i class="fa fa-lg fa-exclamation-circle"></i> joseph broad</a>
  <a href="teaching.html">teaching</a>
  <a href="data.html">data</a>
  <a href="https://www.dropbox.com/s/kyw2nyk7o27fwwy/jbroadcv0419.pdf?dl=0">cv</a>
  <div class="topnav-right"><a href="https://www.linkedin.com/in/joseph-broad-557071a9/"><i class="fa fa-lg fa-linkedin"></i></a>
    <a href="https://twitter.com/therealjoebroad"><i class="fa fa-lg fa-twitter"></i></a>
    <a href="https://github.com/jbroad"><i class="fa fa-lg fa-github"></i></a>
    <a href="mailto:jbroad@ucdavis.edu"><i class="fa fa-lg fa-envelope"></i></a>
    </div>
</div>
</div>

<div class="flex-container" style = "margin-top: 80px;">
  <div class="box">
  <p><font face = "courier">I know how to use these programs.
  </p>
***
<p>images</p>
***
</div>
</div>

<div class="flex-container" style = "margin-top: 180px;">
  <div class="box">
  <p><font face = "courier">To supplement my formal methodological training, I have devoted much of my (limited) free time in graduate school to developing programming skills in creating visually attractive and interactive graphics.
  </p>
***
<iframe src ="https://josephbroad.shinyapps.io/shiny/"
  style="border: 1px; 
  position:absolute;top:0px;left:0px;
  margin-top:100px;
  overflow:hidden;
  width: 100vw; 
  height: 500px;"/>
</iframe>
***
</div>
</div>

<div class="flex-container" style = "margin-top: 680px;">
  <div class="box">
  <p><font face = "courier">
  Social scientists often face serious data limitations that impede research into important questions. Frustrated with these limitations, I learned how to scrape web data and metadata with Python. I have more data than I know what to do with.
  </p>
***
<iframe src ="https://josephbroad.shinyapps.io/shiny/"
  style="border: 1px; 
  position:absolute;top:0px;left:0px;
  margin-top:100px;
  overflow:hidden;
  width: 100vw; 
  height: 500px;"/>
</iframe>
***
</div>
</div>

<div class="flex-container" style = "margin-top: 1180px;">
  <div class="box">
  <p><font face = "courier">
  I have used these skills to develop interactive graphics in order to help my students learn complex statistical concepts, such as Central Limit Theorem, Standard Deviation, Standard Error of the Mean.
  </p>
***
<iframe src ="https://josephbroad.shinyapps.io/stats/"
  style="border: 1px; 
  position:absolute;top:0px;left:0px;
  margin-top:100px;
  overflow:hidden;
  width: 100vw; 
  height: 500px;"/>
</iframe>
***
</div>
</div>

<div class="flex-container" style = "margin-top: 1680px;">
  <div class="box">
  <p><font face = "courier">
  I also try to make abstract statistical concepts more approachable by putting them into the more familiar context of dice rolls in Dungeons and Dragons battle mechanics:
  </p>
***
<iframe src ="https://josephbroad.shinyapps.io/dndstats/"
  style="border: 1px; 
  position:absolute;top:0px;left:0px;
  margin-top:100px;
  overflow:hidden;
  width: 100vw; 
  height: 500px;"/>
</iframe>
***
</div>
</div>




